import Image from "next/image";
import Link from "next/link";
import "./globals.css";
import styles from "./layout.module.css";

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</head>
			<body className={styles.container}>
				<header className={styles.header}>
					<nav>
						<Link href="/">
							<small>Paisaflix</small>
						</Link>
					</nav>
					<Image
            className={styles.avatar}
						width={32}
						height={32}
						src="https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/2b/2b68392c86d120b70aa2e5f32eb40b7aade9e526_full.jpg"
						alt="Paisaflix"
					/>
				</header>
				{children}
				<footer>Should implement a footer</footer>
			</body>
		</html>
	);
}
